#!/bin/bash

S_REPLICA=1
N_REPLICAS=1

for i in $(seq -f "%03g" $S_REPLICA $N_REPLICAS)
        do
	q_genfeps.py input/genfeps.proc \
             ../02-relax/relax_$i/relax_016.inp \
             relax \
	     --rs input/run_feps_q.sh \
             --repeats 10 \
             --frames 51 \
             --fromlambda 0.90 \
             --pdb ../01_preparation/RRDiol.pdb \
             --prefix replica_$i

done
