#!/bin/bash

#q_automapper.py \
#	23.0 \
#	-31.6 \
#	162.217892675 \
#	-49.4227706047 \
#	--nt 1 \
#	--bins 100 \
#	--skip 100 \
#	--min 20 \
#	--temp 298.15 \
#	--dirs ../03-fep_us/replica_* \
#	--out EVB_reference_gas_reaction.log \
#	--qfep_exec Qfep6

q_mapper.py 162.217892675 -49.4227706047 --bins 100 --skip 100 --min 20 --temp 298.15 \
	--dirs ../03-fep/replica_* \
        --out EVB_reference_gas_reaction.log \
        --qfep_exec Qfep6

q_analysefeps.py --lra_l 0.94 0.48 ../03-fep/replica_*

q_plot.py qaf.PlotData.json
#q_geometries_egap.py geometrical_paramaters.data --dirs ../replica_0* --alpha -277.130963097 --pdb ../input/Water_KE.pdb
